apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: join-resources
spec:
  replicas: 3
  selector:
    matchLabel:
      app: join-resources
  template:
    metadata:
      labels: join-resources
    spec:
      - name: backend
        image: pranavsudhirkotawar/backend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
